---
name: CI

on:
  pull_request:


concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  puppet:
    name: Puppet
    uses: evgeni/gha-puppet/.github/workflows/beaker.yml@podman
    with:
      pidfile_workaround: 'true'
      rubocop: false
      cache-version: '1'
